/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:b4dc4181-1746-4bfa-a121-64e0c2ada6a4",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_yIxNfdULS",
    "aws_user_pools_web_client_id": "583uufoda64dr4da3p1g2t4rmj",
    "oauth": {}
};


export default awsmobile;
